 name: Java CI/CD

 on:
   pull_request:
     branches:
       - main
   push:
     branches:
       - main

 jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Set up JDK 17
         uses: actions/setup-java@v2
         with:
           distribution: 'adopt'
           java-version: '17'

       - name: Build with Maven
         run: mvn -B package --file pom.xml

       - name: Run tests
         run: mvn test --file pom.xml

       - name: Upload JAR artifact
         uses: actions/upload-artifact@v2
         with:
           name: app
           path: target/TicTacToe-1.0-SNAPSHOT.jar

   deploy:
     runs-on: ubuntu-latest
     needs: build
     steps:
       # - name: Upload JAR artifact
       #   uses: actions/upload-artifact@v2
       #   with:
       #     name: app
       #     # path: target/TicTacToe.jar
       #     # path: target/TicTacToe-1.0-SNAPSHOT.jar
       #     path: target/TicTacToe-1.0-SNAPSHOT.jar
       #     if-no-files-found: error

       - name: Set up JDK 17 for deployment
         uses: actions/setup-java@v2
         with:
           distribution: 'adopt'
           java-version: '17'

       - name: Download JAR artifact
         uses: actions/download-artifact@v2
         with:
           name: app
           # path: target/
           path: target/

       - name: Deploy to GitHub Releases
         id: deploy
         uses: softprops/action-gh-release@v1
         with:
           files: target/TicTacToe-1.0-SNAPSHOT.jar
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
